### ISSUE TITLE
avatar not showing fallback icon when source prop becomes undefined/null

### ISSUE THREAD

**Issue by sam1463** [react-native-elements/react-native-elements#2143]
**Explain what you did**
I'm using an Avatar component with an image source and an icon as a fallback for a profile picture. If the image source is initially set to be undefined (i.e. no profile photo), the Avatar renders correctly with the icon, and if it has a source image, that renders correctly too.

**Expected behaviour**
I would expect the Avatar to render the icon when the source prop is removed and the component rerenders.

**Describe the bug**
If there is initially an image, and then it's removed (use case here is a profile photo, and the user removing the profile picture), when the source prop becomes undefined, the avatar doesn't render the icon, just a background with no icon and no image (tried using `renderPlaceholderContent` and it doesn't render that either in this case).

**Comment by iRoachie** [comment]
This is already fixed on `next`. And will be live in 2.0.0. The problem was that previously there was an extra grey background applied to the `Image` component underneath. 

So the avatar was setting one on the container style - https://github.com/react-native-elements/react-native-elements/blob/master/src/avatar/Avatar.js#L165

And then the Image component has one of its own for the placeholder - https://github.com/react-native-elements/react-native-elements/blob/master/src/image/Image.js#L103

Now it's only on the placeholder style as it should.

**Comment by njdullea** [comment]
How can you install `next`, or when will `2.0.0` be released?

I tried `yarn upgrade react-native-elements@next` but was just presented a list of versions up to `1.2.7`.

**Comment by gouravpal1991** [comment]
The issue is not fixed for android.

**Comment by gouravpal1991** [comment]
<ListItem
        title={item.vendorName}
        subtitle={item.addressLine}
        leftAvatar={{
          source: {uri: item.categoryURI},
          title: title,
        }}
        bottomDivider
        chevron
      />

**Comment by rogger-frogger** [comment]
This issue is still present on    "react-native-elements": "^2.0.1",

**Comment by bravemaster619** [comment]
According to [doc](https://react-native-elements.github.io/react-native-elements/docs/avatar.html), the following html should render placeholder with title MD:

```javascript
// Avatar with Title
<Avatar rounded title="MD" />
```

However, it doesn't show anything.

If you give some random string to `source.uri`, then it will render placeholder:

```javascript
<Avatar
  rounded
  source={{uri: "foo.jpg"}}
  title="MD"
/>
```

I've tested in iOS and `react-native-elements` version is 2.0.1

**Comment by Bilal-Abdeen** [comment]
Based on @bravemaster619 comment (above), I came up with the following workaround, which seems to work for now! 
```
leftAvatar={{
	// When "item.imageURI" is null, assign an arbitrary value! This seems to initiate the use of the fallback title! 
	source: (item.imageURI ? { uri: item.imageURI } : { uri: "abc.abc" }),

	title: "BA",
}}
```

**Comment by bravemaster619** [comment]
> Based on @bravemaster619 comment (above), I came up with the following workaround, which seems to work for now!
> 
> ```
> leftAvatar={{
> 	// When "item.imageURI" is null, assign an arbitrary value! This seems to initiate the use of the fallback title! 
> 	source: (item.imageURI ? { uri: item.imageURI } : { uri: "abc.abc" }),
> 
> 	title: "BA",
> }}
> ```

Just passing empty string would be sufficient enough. However, you will see yellow box that says `soure.uri` should never be an empty string

**Comment by JRamonMC** [comment]
Any updates here? I've tried 
` <Avatar rounded  title={user_name.slice(0,1)}>`
But doesn't work, nothing happens

**Comment by tylerolechnowicz** [comment]
Passing an empty string did not fix the issue for me. The Avatar component appears as 'blank', just white.

**Comment by vuciv** [comment]
Bump, this issue is still not fixed on android.

**Comment by Death14Stroke** [comment]
I am facing the exact same issue on my Android device. Is there any other library offering the same component?

**Comment by mariahmartinez** [comment]
Still experiencing this bug. 

The workaround that @Bilal-Abdeen and @bravemaster619  posted is working. I'd rather not just pass some random uri though.

**Comment by josegoval** [comment]
> Still experiencing this bug.
> 
> The workaround that @Bilal-Abdeen and @bravemaster619 posted is working. I'd rather not just pass some random uri though.

My solution
```
<Avatar
          source={
            user?.imageId
              ? {
                  uri: getUserImageRoute(user.imageId),
                  headers: {Authorization: jwt},
                }
              : {uri: 'no-image'}
          }
          rounded
          title={getInitials(user?.name || 'AA')}
          placeholderStyle={{backgroundColor: colors.THIRD}}
          titleStyle={{color: 'black'}}
        />
```

**Comment by ZeeshanAhmadKhalil** [comment]
Solution that worked for me is giving `backgroundColor: "silver"` to `containerStyle` as follows:

`<Avatar
                        key={key}
                        rounded
                        source={{
                            uri: baseURL + "/Images/" + profilePicPath,
                        }}
                        title={fullName.charAt(0)}
                        size="medium"
                        containerStyle={{
                            backgroundColor: "silver",
                        }}
                    />`

**Comment by Bilal-Abdeen** [comment]
Using `uri: "abc.abc"` seems to cause a warning message, these days. I played around with the suggested solutions above. I reached the following conclusion. 

If none of the data records has an image: 
```javascript
<Avatar 
        // do NOT assign any value to the source property 
	containerStyle={{ backgroundColor: "silver", }} // or whatever color you like 
        .... 
/> 
```

If some of the records have an image while others do not:
```javascript
<Avatar 
        source={( item.imageURI ? { uri: item.imageURI } : null )}
	containerStyle={{ backgroundColor: "silver", }} // or whatever color you like 
        .... 
/> 
```

Obviously, you can add `containerStyle={{ backgroundColor: "silver", }}` to your theme file. 

react-native: 0.70.1
react-native-elements: 3.4.2

**Comment by FedericoRubinstein** [comment]
Bump. 
I have a similar issue in 4.0.0. 
My code:
```
<Avatar
        size={avatarSize}
        containerStyle={styles.avatarContainer}
        titleStyle={styles.avatarText}
        rounded
        source={{ uri: photoURL !== "" ? photoURL : undefined }}
        title={getInitials(name ?? "")}
      />
```
Originally, `photoURL = ""`, when I change it to a correct URI the image loads correctly, however if I change it back to "" or `undefined` the photo still renders with the title on top. I would expect the photo to stop rendering and only show the title. Solutions above did not work, and changing photoURL to a random string triggers a warning.

Any solutions?

**Comment by FedericoRubinstein** [comment]
Interestingly enough, rending the Avatar component conditionally with and without photoURL also doesn't work:
```
{photoURL && photoURL !== "" ? (
        <RNEAvatar
          source={{ uri: photoURL }}
          ...
        />
      ) : (
        <RNEAvatar
          title={getInitials(name ?? "")}
          ...
        />
      )}
```
