### ISSUE TITLE
Image Component very slow compared to the RN default one

### ISSUE THREAD

**Issue by xstable** [react-native-elements/react-native-elements#2427]
**Explain what you did**
Implement <Image> in a ListItem. The Image is not an URL, but an local file, bundled with the app.

**Expected behavior**
Should load faster (like default <Image> from RN does!

**Describe the bug**
The loading of an Image is slow. As long as the image load, there is a gray background.

**Videos**
See videos. First one is RN Default <Image>-Component.
Second one is RN-Elements one.

https://imgur.com/a/QjuYoLb

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   ^2.0.4      |
| react-native          |   ^0.60.5      |

**Comment by flyingcircle** [comment]
I think will actually require a breaking change so it'll have to wait for 3.0

**Comment by pranshuchittora** [comment]
@flyingcircle I think the two main reasons for such performance issue are:-
1. Not using proper react lifecycle methods.
2. Using setTimeout https://github.com/react-native-elements/react-native-elements/blob/b0590e1a5efd3456861b03bbc61601733adaed7a/src/image/Image.js#L34

**Comment by akhatriST** [comment]
@flyingcircle  Since the fix has been merged, will it be available before 3.0.0 ?

**Comment by flyingcircle** [comment]
@akhatriST yes. We're hoping to wrap up the 3.0 release by end of next week.

**Comment by akhatriST** [comment]
@flyingcircle Sounds great

**Comment by jorgegvallejo** [comment]
I'm still experiencing this in v4.0.0.RC.4 even with `transition:false`. Anybody else?
